<?php
//开启debug
define('APP_DEBUG',true);
//定义项目名称
define('APP_NAME','Home');
//定义项目路径
define('APP_PATH','./Home/');
//引入高级session类文件
require('./Public/Functions/memsession.class.php');
//引入thinkphp配置文件
require('./ThinkPHP/ThinkPHP.php');
